baseURL = "https://marcriera.github.io/ddgo-controller-docs"
languageCode = "en-us"
title = "Densha de GO! controller documentation"
theme = "relearn"
canonifyURLs = true

[params]
disableSearch = true
themeVariant = [ "relearn-light", "relearn-dark" ]
collapsibleMenu = true
disableLandingPageButton = true
disableShortcutsTitle=true
disableNextPrev = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Acknowledgements"
url = "/acknowledgements"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> References"
url = "/references"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repository"
url = "https://github.com/MarcRiera/ddgo-controller-docs"
weight = 3
